[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "basic-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["alpha-core"]

[tool.uv.sources]
alpha-core = { workspace = true }

[project.scripts]
basic-app = "basic_app.main:run"
workspace-demo = "basic_app.main:run_workspace_demo"


