[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "basic-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alpha-core",
    "pydantic>=2.13.4",
]

[tool.uv.sources]
alpha-core = { workspace = true }

[project.scripts]
basic-app = "basic_app.main:run"
eval-demo = "basic_app.main:run_eval_demo"
doc-gen = "basic_app.main:run_doc_gen_demo"


