/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as EvalsRouteImport } from './routes/evals'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows.index'
import { Route as EvalsIndexRouteImport } from './routes/evals.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as WorkspaceSandboxesRouteImport } from './routes/workspace.sandboxes'
import { Route as WorkspaceFileSystemsRouteImport } from './routes/workspace.file-systems'
import { Route as WorkflowsStepsRouteImport } from './routes/workflows.steps'
import { Route as EvalsScorersRouteImport } from './routes/evals.scorers'
import { Route as AgentsToolsRouteImport } from './routes/agents.tools'
import { Route as AgentsInterfacesRouteImport } from './routes/agents.interfaces'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsRoute = EvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowsRoute,
} as any)
const EvalsIndexRoute = EvalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EvalsRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const WorkspaceSandboxesRoute = WorkspaceSandboxesRouteImport.update({
  id: '/sandboxes',
  path: '/sandboxes',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceFileSystemsRoute = WorkspaceFileSystemsRouteImport.update({
  id: '/file-systems',
  path: '/file-systems',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkflowsStepsRoute = WorkflowsStepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => WorkflowsRoute,
} as any)
const EvalsScorersRoute = EvalsScorersRouteImport.update({
  id: '/scorers',
  path: '/scorers',
  getParentRoute: () => EvalsRoute,
} as any)
const AgentsToolsRoute = AgentsToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsInterfacesRoute = AgentsInterfacesRouteImport.update({
  id: '/interfaces',
  path: '/interfaces',
  getParentRoute: () => AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/evals': typeof EvalsRouteWithChildren
  '/workflows': typeof WorkflowsRouteWithChildren
  '/workspace': typeof WorkspaceRouteWithChildren
  '/agents/interfaces': typeof AgentsInterfacesRoute
  '/agents/tools': typeof AgentsToolsRoute
  '/evals/scorers': typeof EvalsScorersRoute
  '/workflows/steps': typeof WorkflowsStepsRoute
  '/workspace/file-systems': typeof WorkspaceFileSystemsRoute
  '/workspace/sandboxes': typeof WorkspaceSandboxesRoute
  '/agents/': typeof AgentsIndexRoute
  '/evals/': typeof EvalsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/interfaces': typeof AgentsInterfacesRoute
  '/agents/tools': typeof AgentsToolsRoute
  '/evals/scorers': typeof EvalsScorersRoute
  '/workflows/steps': typeof WorkflowsStepsRoute
  '/workspace/file-systems': typeof WorkspaceFileSystemsRoute
  '/workspace/sandboxes': typeof WorkspaceSandboxesRoute
  '/agents': typeof AgentsIndexRoute
  '/evals': typeof EvalsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/evals': typeof EvalsRouteWithChildren
  '/workflows': typeof WorkflowsRouteWithChildren
  '/workspace': typeof WorkspaceRouteWithChildren
  '/agents/interfaces': typeof AgentsInterfacesRoute
  '/agents/tools': typeof AgentsToolsRoute
  '/evals/scorers': typeof EvalsScorersRoute
  '/workflows/steps': typeof WorkflowsStepsRoute
  '/workspace/file-systems': typeof WorkspaceFileSystemsRoute
  '/workspace/sandboxes': typeof WorkspaceSandboxesRoute
  '/agents/': typeof AgentsIndexRoute
  '/evals/': typeof EvalsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/evals'
    | '/workflows'
    | '/workspace'
    | '/agents/interfaces'
    | '/agents/tools'
    | '/evals/scorers'
    | '/workflows/steps'
    | '/workspace/file-systems'
    | '/workspace/sandboxes'
    | '/agents/'
    | '/evals/'
    | '/workflows/'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents/interfaces'
    | '/agents/tools'
    | '/evals/scorers'
    | '/workflows/steps'
    | '/workspace/file-systems'
    | '/workspace/sandboxes'
    | '/agents'
    | '/evals'
    | '/workflows'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/evals'
    | '/workflows'
    | '/workspace'
    | '/agents/interfaces'
    | '/agents/tools'
    | '/evals/scorers'
    | '/workflows/steps'
    | '/workspace/file-systems'
    | '/workspace/sandboxes'
    | '/agents/'
    | '/evals/'
    | '/workflows/'
    | '/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  EvalsRoute: typeof EvalsRouteWithChildren
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals': {
      id: '/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof EvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/evals/': {
      id: '/evals/'
      path: '/'
      fullPath: '/evals/'
      preLoaderRoute: typeof EvalsIndexRouteImport
      parentRoute: typeof EvalsRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/workspace/sandboxes': {
      id: '/workspace/sandboxes'
      path: '/sandboxes'
      fullPath: '/workspace/sandboxes'
      preLoaderRoute: typeof WorkspaceSandboxesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/file-systems': {
      id: '/workspace/file-systems'
      path: '/file-systems'
      fullPath: '/workspace/file-systems'
      preLoaderRoute: typeof WorkspaceFileSystemsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workflows/steps': {
      id: '/workflows/steps'
      path: '/steps'
      fullPath: '/workflows/steps'
      preLoaderRoute: typeof WorkflowsStepsRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/evals/scorers': {
      id: '/evals/scorers'
      path: '/scorers'
      fullPath: '/evals/scorers'
      preLoaderRoute: typeof EvalsScorersRouteImport
      parentRoute: typeof EvalsRoute
    }
    '/agents/tools': {
      id: '/agents/tools'
      path: '/tools'
      fullPath: '/agents/tools'
      preLoaderRoute: typeof AgentsToolsRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/interfaces': {
      id: '/agents/interfaces'
      path: '/interfaces'
      fullPath: '/agents/interfaces'
      preLoaderRoute: typeof AgentsInterfacesRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsInterfacesRoute: typeof AgentsInterfacesRoute
  AgentsToolsRoute: typeof AgentsToolsRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsInterfacesRoute: AgentsInterfacesRoute,
  AgentsToolsRoute: AgentsToolsRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface EvalsRouteChildren {
  EvalsScorersRoute: typeof EvalsScorersRoute
  EvalsIndexRoute: typeof EvalsIndexRoute
}

const EvalsRouteChildren: EvalsRouteChildren = {
  EvalsScorersRoute: EvalsScorersRoute,
  EvalsIndexRoute: EvalsIndexRoute,
}

const EvalsRouteWithChildren = EvalsRoute._addFileChildren(EvalsRouteChildren)

interface WorkflowsRouteChildren {
  WorkflowsStepsRoute: typeof WorkflowsStepsRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsStepsRoute: WorkflowsStepsRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

interface WorkspaceRouteChildren {
  WorkspaceFileSystemsRoute: typeof WorkspaceFileSystemsRoute
  WorkspaceSandboxesRoute: typeof WorkspaceSandboxesRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceFileSystemsRoute: WorkspaceFileSystemsRoute,
  WorkspaceSandboxesRoute: WorkspaceSandboxesRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  EvalsRoute: EvalsRouteWithChildren,
  WorkflowsRoute: WorkflowsRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
